export const MEETER_DEFAULTS = {
    ORGANIZATION_ID: 'c9d00915-fc0c-4f0e-ac23-d75acd1b80e2',
    CODE: 'mtr',
    NAME: 'Meeter Test System',
    HERO_MESSAGE:
        'Thanks for helping! You make this better. None of us are better than all of us!',
    ROLE: 'new',
};

export const PHONE_REGX =
    /^[(]{0,1}[0-9]{3}[)]{0,1}[-\s\.]{0,1}[0-9]{3}[-\s\.]{0,1}[0-9]{4}$/;

export const EVENT_STATUS = Object.freeze({
    DRAFT: 'Draft',
    PENDING: 'Pending',
    APPROVED: 'Approved',
});
export const MONTH_STRINGS = [
    '',
    'JAN',
    'FEB',
    'MAR',
    'APR',
    'MAY',
    'JUN',
    'JUL',
    'AUG',
    'SEP',
    'OCT',
    'NOV',
    'DEC',
];
export const DEFAULT_AFFILIATIONS = Object.freeze({
    affiliations: {
        active: {
            label: 'Meeter Test System',
            role: 'guest',
            value: 'mtr',
        },
        options: [
            {
                label: 'Meeter Test System',
                role: 'guest',
                value: 'mtr',
            },
        ],
    },
});
export const SHIRTSIZESBYWORDS = [
    { label: 'Small', value: 'S' },
    { label: 'Medim', value: 'M' },
    { label: 'Large', value: 'L' },
    { label: 'X-Large', value: 'XL' },
    { label: '2X-Large', value: 'XXL' },
    { label: '3X-Large', value: 'XXXL' },
    { label: '4X-Large', value: 'XXXXL' },
];
export const SHIRTSIZESBY2 = [
    { label: 'SM', value: 'S' },
    { label: 'MD', value: 'M' },
    { label: 'LG', value: 'L' },
    { label: 'XL', value: 'XL' },
    { label: '2X', value: 'XXL' },
    { label: '3X', value: 'XXXL' },
    { label: '4X', value: 'XXXXL' },
];
const STATELABELVALUES = [
    { label: 'Alabama', value: 'AL' },
    { label: 'Alaska', value: 'AK' },
    { label: 'American Samoa', value: 'AS' },
    { label: 'Arizona', value: 'AZ' },
    { label: 'Arkansas', value: 'AR' },
    { label: 'California', value: 'CA' },
    { label: 'Colorado', value: 'CO' },
    { label: 'Connecticut', value: 'CT' },
    { label: 'Delaware', value: 'DE' },
    { label: 'District of Columbia', value: 'DC' },
    { label: 'Florida', value: 'FL' },
    { label: 'Georgia', value: 'GA' },
    { label: 'Guam', value: 'GU' },
    { label: 'Hawaii', value: 'HI' },
    { label: 'Idaho', value: 'ID' },
    { label: 'Illinois', value: 'IL' },
    { label: 'Indiana', value: 'IN' },
    { label: 'Iowa', value: 'IA' },
    { label: 'Kansas', value: 'KS' },
    { label: 'Kentucky', value: 'KY' },
    { label: 'Louisiana', value: 'LA' },
    { label: 'Maine', value: 'ME' },
    { label: 'Maryland', value: 'MD' },
    { label: 'Massachusetts', value: 'MA' },
    { label: 'Michigan', value: 'MI' },
    { label: 'Minnesota', value: 'MN' },
    { label: 'Mississippi', value: 'MS' },
    { label: 'Missouri', value: 'MO' },
    { label: 'Montana', value: 'MT' },
    { label: 'Nebraska', value: 'NE' },
    { label: 'Nevada', value: 'NV' },
    { label: 'New Hampshire', value: 'NH' },
    { label: 'New Jersey', value: 'NJ' },
    { label: 'New Mexico', value: 'NM' },
    { label: 'New York', value: 'NY' },
    { label: 'North Carolina', value: 'NC' },
    { label: 'North Dakota', value: 'ND' },
    { label: 'Ohio', value: 'OH' },
    { label: 'Oklahoma', value: 'OK' },
    { label: 'Oregon', value: 'OR' },
    { label: 'Pennsylvania', value: 'PA' },
    { label: 'Puerto Rico', value: 'PR' },
    { label: 'Rhode Island', value: 'RI' },
    { label: 'South Carolina', value: 'SC' },
    { label: 'South Dakota', value: 'SD' },
    { label: 'Tennessee', value: 'TN' },
    { label: 'Texas', value: 'TX' },
    { label: 'Utah', value: 'UT' },
    { label: 'Vermont', value: 'VT' },
    { label: 'Virgin Islands', value: 'VI' },
    { label: 'Virginia', value: 'VA' },
    { label: 'Washington', value: 'WA' },
    { label: 'West Virginia', value: 'WV' },
    { label: 'Wisconsin', value: 'WI' },
    { label: 'Wyoming', value: 'WY' },
];
export const STATESBY2 = [
    { label: 'AL', value: 'AL' },
    { label: 'AK', value: 'AK' },
    { label: 'AZ', value: 'AZ' },
    { label: 'AR', value: 'AR' },
    { label: 'CA', value: 'CA' },
    { label: 'CO', value: 'CO' },
    { label: 'CT', value: 'CT' },
    { label: 'DE', value: 'DE' },
    { label: 'FL', value: 'FL' },
    { label: 'GA', value: 'GA' },
    { label: 'HI', value: 'HI' },
    { label: 'ID', value: 'ID' },
    { label: 'IL', value: 'IL' },
    { label: 'IN', value: 'IN' },
    { label: 'IA', value: 'IA' },
    { label: 'KS', value: 'KS' },
    { label: 'KY', value: 'KY' },
    { label: 'LA', value: 'LA' },
    { label: 'ME', value: 'ME' },
    { label: 'MD', value: 'MD' },
    { label: 'MA', value: 'MA' },
    { label: 'MI', value: 'MI' },
    { label: 'MN', value: 'MN' },
    { label: 'MS', value: 'MS' },
    { label: 'MO', value: 'MO' },
    { label: 'MT', value: 'MT' },
    { label: 'NE', value: 'NE' },
    { label: 'NV', value: 'NV' },
    { label: 'NH', value: 'NH' },
    { label: 'NJ', value: 'NJ' },
    { label: 'NM', value: 'NM' },
    { label: 'NY', value: 'NY' },
    { label: 'NC', value: 'NC' },
    { label: 'ND', value: 'ND' },
    { label: 'OH', value: 'OH' },
    { label: 'OK', value: 'OK' },
    { label: 'OR', value: 'OR' },
    { label: 'PA', value: 'PA' },
    { label: 'RI', value: 'RI' },
    { label: 'SC', value: 'SC' },
    { label: 'SD', value: 'SD' },
    { label: 'TN', value: 'TN' },
    { label: 'TX', value: 'TX' },
    { label: 'UT', value: 'UT' },
    { label: 'VT', value: 'VT' },
    { label: 'VA', value: 'VA' },
    { label: 'WA', value: 'WA' },
    { label: 'WV', value: 'WV' },
    { label: 'WI', value: 'WI' },
    { label: 'WY', value: 'WY' },
];
export const newMeetingTemplate = {
    childrenCount: 0,
    transportationContact: '',
    mealCount: 0,
    meal: '',
    greeterContact2: '',
    nurseryCount: 0,
    greeterContact1: '',
    securityContact: '',
    announcementsContact: '',
    attendanceCount: 0,
    mealContact: '',
    closingContact: '',
    notes: '',
    cafeCount: 0,
    youthCount: 0,
    cafeContact: '',
    setupContact: '',
    meetingDate: '',
    donations: 0,
    youthContact: '',
    nurseryContact: '',
    cleanupContact: '',
    resourceContact: '',
    childrenContact: '',
    newcomersCount: 0,
    mtgCompKey: '',
    facilitatorContact: '',
    transportationCount: 0,
    worship: '',
    avContact: '',
    supportContact: '',
    meetingType: 'Testimony',
    title: '',
};
export const DEFAULT_MEETING = {
    id: null,
    created_at: null,
    updated_at: null,
    meeting_date: null,
    title: null,
    meeting_type: null,
    mtg_comp_key: null,
    announcements_contact: null,
    attendance_count: null,
    av_contact: null,
    cafe_contact: null,
    cafe_count: null,
    children_contact: null,
    children_count: null,
    cleanup_contact: null,
    closing_contact: null,
    donations: null,
    facilitator_contact: null,
    greeter_contact1: null,
    greeter_contact2: null,
    meal: null,
    meal_contact: null,
    meal_count: null,
    newcomers_count: null,
    notes: null,
    nursery_contact: null,
    nursery_count: null,
    resource_contact: null,
    security_contact: null,
    setup_contact: null,
    support_contact: null,
    transportation_contact: null,
    transportation_count: null,
    worship: null,
    youth_contact: null,
    youth_count: null,
    organization_id: null,
    aws_id: null,
    aws_org_id: null,
};
export const monthCodes = {
    '01': 'JAN',
    '02': 'FEB',
    '03': 'MAR',
    '04': 'APR',
    '05': 'MAY',
    '06': 'JUN',
    '07': 'JUL',
    '08': 'AUG',
    '09': 'SEP',
    10: 'OCT',
    11: 'NOV',
    12: 'DEC',
};
export const GenderStrings = {
    m: "Men's",
    f: "Women's",
    x: 'Mixed',
};
