// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_appsync_graphqlEndpoint:
        'https://tn75t3gxyfcr5ojcdfep3eqhqa.appsync-api.us-east-1.amazonaws.com/graphql',
    aws_appsync_region: 'us-east-1',
    aws_appsync_authenticationType: 'API_KEY',
    aws_appsync_apiKey: 'da2-7d5vx4dktnh6vfnttjhqgxclke',
    aws_cognito_identity_pool_id:
        'us-east-1:5568f877-2766-4ea3-a9a6-442df0d29980',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_XM4WXQ6lj',
    aws_user_pools_web_client_id: '6fe26lh1hpvpvs73uk5qt50g57',
    oauth: {
        domain: 'meeter2.auth.us-east-1.amazoncognito.com',
    },
    aws_cognito_username_attributes: [],
    aws_cognito_social_providers: [],
    aws_cognito_signup_attributes: ['EMAIL'],
    aws_cognito_mfa_configuration: 'OPTIONAL',
    aws_cognito_mfa_types: ['TOTP'],
    aws_cognito_password_protection_settings: {
        passwordPolicyMinLength: 8,
        passwordPolicyCharacters: [
            'REQUIRES_LOWERCASE',
            'REQUIRES_UPPERCASE',
            'REQUIRES_NUMBERS',
            'REQUIRES_SYMBOLS',
        ],
    },
    aws_cognito_verification_mechanisms: ['EMAIL'],
    aws_user_files_s3_bucket: 'jerichosystems3files170250-staging',
    aws_user_files_s3_bucket_region: 'us-east-1',
    aws_user_files_s3_bucket_pageSize: 100,
};

export default awsmobile;
