// Color palette
const Colors = {
    primaryBackground: '#1D5D9B',
    secondary: '#1CD6CE',
    primary: '#CAEBF2',
    accent: '#F4D160',
    activityIndicator: '#293462',
    alternate: '#D61C4E',
    errorTextBox: '#F08080',
    historyTile: '#ffffff',
    dark: '#000000',
    date: '#1D5D9B',
    light: '#ffffff',
    lightGrey: '#D3D3D3',
    link: '#F2A310',
    blue: '#578CFE',
    darkText: '#000',
    lightText: '#ffffff',
    mediumText: '#999999',
    yellow: '#F0DE36',
    red: '#D61C4E',
    green: '#00ff00',
    white: '#ffffff',
    menuText: '#ffffff',
    unselectedBackground: '#1D5D9B',
    unselectedText: '#ffffff',
    selectedBackground: '#CAEBF2',
    selectedText: '#000000',
};

const theme = {
    dark: true,
    mode: 'exact',
    roundness: 50,
    // Specify custom property in nested object
    colors: {
        ...Colors,
        menuText: Colors.menuText,
        surface: Colors.primaryBackground,
        text: Colors.white,
        disabled: '#cccccc',
        placeholder: 'lightgrey',
        backdrop: Colors.white,
        onSurface: Colors.yellow,
        landingAppName: Colors.accent,
        success: '#008000',
        warning: Colors.yellow,
        critical: Colors.red,
        errorTextBox: Colors.errorTextBox,
        notification: Colors.red,
        navActive: Colors.red,
        navInactive: '#8c8c8c',
        cardBackground: Colors.lightGrey,
        cardText: Colors.darkText,
        black: Colors.dark,
        lightGraphic: Colors.lightText,
        link: Colors.link,
        mediumGraphic: Colors.mediumText,
        darkGraphic: Colors.darkText,
        editScreenHeader: '#293462',
        selected: '#293462',
        unSelected: '#8c8c8c',
        unSelectedText: Colors.white,
        navBarInactiveBackground: '#293462',
        navBarInactiveText: Colors.primary,
        navBarActiveBackground: Colors.primary,
        navBarActiveText: Colors.darkText,
        navDrawerActiveBackground: Colors.red,
        musicIcon: Colors.blue,
        navDrawerActiveTint: Colors.white,
        navDrawerInactiveBackground: Colors.white,
        navDrawerInactiveTint: Colors.mediumText,
        lightBlue: Colors.blue,
        buttonTextLight: Colors.white,
        buttonTextDark: Colors.primaryBackground,
        buttonFillLight: '#8CABFF',
        buttonFillMedium: '#4477CE',
        buttonFillDark: '#512B81',
        buttonFillDarker: '#35155D',
        meetingActiveCard: Colors.primary,
        meetingHistoricCard: '#cccccc',
        groupActiveCard: Colors.primary,
        groupHistoricCard: '#cccccc',
        screenTitleTextLight: Colors.primary,
        screenTitleTextDark: Colors.primaryBackground,
    },
};

export default theme;
