import theme from '@assets/Colors';
const themedStyles: { [key: string]: any } = {
    calendarTheme: {
        backgroundColor: '#003366',
        calendarBackground: '#003366',
        textSectionTitleColor: theme.colors.accent, // days of the week
        selectedDayBackgroundColor: 'black',
        // selectedDayTextColor: 'black', // selected background
        todayTextColor: theme.colors.accent,
        dayTextColor: 'white',
        textDisabledColor: '#888',
        monthTextColor: '#fff',
        arrowColor: '#007AFF',
    },
    cardActiveMeetingPrimary: {
        backgroundColor: theme.colors.activeCard,
    },
    cardColumnCenter: {
        justifyContent: 'center',
    },
    cardColumnDate: {
        padding: 5,
    },
    cardColumnIcons: {
        paddingRight: 5,
        alignItems: 'center',
        justifyContent: 'space-between',
        marginVertical: 5,
    },
    cardColumnText: {
        flex: 1,
        paddingHorizontal: 8,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    cardDateContainer: {
        padding: 1,
    },
    cardDefinitionContainer: {
        flex: 1,
    },
    cardFirstRow: {
        flexDirection: 'row',
        flex: 1,
        marginHorizontal: 5,
        alignItems: 'center',
    },
    cardHistoricMeetingPrimary: {
        backgroundColor: theme.colors.historicCard,
    },
    cardIconContainer: {
        marginTop: 10,
        marginRight: 10,
        alignItems: 'flex-end',
    },
    cardMeetingItem: {
        marginVertical: 5,
        paddingBottom: 5,
        backgroundColor: theme.colors.darkShadow,
        flexDirection: 'row',
        flex: 1,
        borderRadius: 10,
        elevation: 3,
        shadowColor: theme.colors.darkShadow,
        shadowRadius: 4,
        shadowOffset: { width: 1, height: 1 },
        shadowOpacity: 0.4,
    },
    cardMeetingTypeText: {
        fontFamily: 'Roboto-Regular',
        fontSize: 26,
        fontWeight: '600',
    },
    cardRootContainer: {
        marginHorizontal: 10,
    },
    container: {
        flex: 1,
        flexDirection: 'column' as 'column',
        backgroundColor: theme.colors.primaryBackground,
    },
    containerContents: {
        paddingTop: 5,
        paddingHorizontal: 10,
    },
    dateContainer: { margin: 5 },
    firstRow: {
        flexDirection: 'row' as 'row',
        alignItems: 'center' as 'center',
        justifyContent: 'center' as 'center',
        padding: 0,
        marginVertical: 0,
        marginHorizontal: 0,
    },
    formInput: {
        fontFamily: 'Roboto-Regular',
        fontSize: 16,
        //what
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 6,
        padding: 8,
        marginBottom: 8,
        backgroundColor: '#fff',
    },
    formLabel: {
        fontFamily: 'Roboto-Regular',
        fontSize: 18,
        color: theme.colors.lightText,
        paddingVertical: 0,
    },
    keyboardAvoiding: {
        flex: 1,
    },
    logisticsWrapper: {
        flexDirection: 'row' as 'row',
        borderWidth: 2,
        borderColor: theme.colors.darkText, // Use the darkText variable directly, same as darkGraphic',
        borderRadius: 5,
        backgroundColor: theme.colors.white,
        paddingVertical: 5,
        marginHorizontal: 10,
    },
    mealContainer: {
        flexDirection: 'column' as 'column',
        borderWidth: 2,
        borderColor: theme.colors.lightGraphic, // Use the darkText variable directly, same as darkGraphic',
        borderRadius: 5,
        // backgroundColor: theme.colors.white,
        marginVertical: 0,
        // paddingVertical: 5,
        padding: 5,
        marginHorizontal: 10,
    },
    mealSectionContainer: {
        flex: 1,
        borderWidth: 1,
        borderColor: theme.colors.darkText,
        borderRadius: 10,
        padding: 5,
        marginHorizontal: 10,
        marginVertical: 5,
    },
    mealSectionCountLabelContainer: {
        paddingTop: 5,
        alignItems: 'center',
    },
    mealSectionCountLabelText: {
        fontFamily: 'Roboto-Regular',
        color: theme.colors.darkText,
        fontSize: 18,
        textAlign: 'center',
    },
    mealSectionInputLabel: {
        fontFamily: 'Roboto-Regular',
        color: theme.colors.darkText,
        fontSize: 18,
        marginLeft: 10,
    },
    mealSectionTitleText: {
        fontFamily: 'Roboto-Regular',
        color: theme.colors.darkText,
        fontSize: 20,
    },
    mealWrapper: {
        flexDirection: 'row' as 'row',
        borderWidth: 2,
        borderColor: theme.colors.darkText, // Use the darkText variable directly, same as darkGraphic',
        borderRadius: 5,
        backgroundColor: theme.colors.white,
        marginVertical: 0,
        paddingVertical: 5,
        marginHorizontal: 10,
    },
    meetingDateRow: {
        marginVertical: 2,
    },
    meetingListError: {
        color: theme.colors.white,
        fontWeight: 'bold' as 'bold',
        backgroundColor: theme.colors.accent,
        padding: 12,
        borderRadius: 8,
    },
    meetingNotesContainer: {
        marginTop: 10,
        marginHorizontal: 10,
    },
    meetingSelectorContainer: {
        flex: 1,
        alignItems: 'center' as 'center',
        justifyContent: 'center' as 'center',
        marginBottom: 0,
    },
    meetingSelectorWrapper: {
        flexDirection: 'row' as 'row',
        borderWidth: 2,
        borderColor: theme.colors.darkText, // Use the darkText variable directly, same as darkGraphic',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        backgroundColor: theme.colors.lightGraphic,
        // marginTop: 5,
        paddingVertical: 0,
        marginHorizontal: 0,
    },
    meetingTypeSelectorSelected: {
        backgroundColor: theme.colors.accent,
        borderWidth: 0,
    },
    meetingTypeSelectorSelectedText: {
        color: theme.colors.darkText,
    },
    meetingTypeSelectorUnselected: {
        paddingHorizontal: 8,
        paddingVertical: 6,
        borderRadius: 4,
        backgroundColor: theme.colors.unSelected,
        alignSelf: 'flex-start' as 'flex-start',
        marginHorizontal: '1%',
        minWidth: '30%',
        textAlign: 'center' as 'center',
    },
    meetingTypeSelectorUnselectedText: {
        fontSize: 16,
        fontWeight: '500',
        color: theme.colors.unSelectedText,
        textAlign: 'center' as 'center',
    },
    meetingsContainer: {
        flex: 1,
        alignItems: 'center' as 'center',
        paddingTop: 48,
    },
    meetingsText: {
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center' as 'center',
        marginBottom: 16,
    },
    meetingsItemContainer: {
        width: '100%',
        paddingHorizontal: 15,
        marginVertical: 8,
    },
    modal: {
        flex: 1,
        flexDirection: 'column' as 'column',
        alignItems: 'center' as 'center',
        justifyContent: 'center' as 'center',
        backgroundColor: theme.colors.primaryBackground,
    },
    modalDateContainer: { marginTop: 20 },
    modalDateText: {
        fontSize: 24,
        fontFamily: 'Roboto-Bold',
        textAlign: 'center' as 'center',
    },
    modalHeaderContainer: {
        backgroundColor: theme.colors.primaryBackground,
    },
    modalHeaderText: {
        fontFamily: 'Roboto-Bold' as 'Roboto-Bold',
        fontSize: 28,
        fontWeight: '700',
        color: theme.colors.lightText,
        textAlign: 'center' as 'center',
        paddingTop: 10,
    },
    modalMeetingInfoContainer: {},
    modalMeetingInfoText: {
        fontSize: 18,
        fontFamily: 'Roboto-Medium',
        textAlign: 'center' as 'center',
    },
    modalNoteContainer: {
        marginHorizontal: 20,
    },
    modalNoteText: {
        paddingTop: 20,
        fontSize: 16,
        fontFamily: 'Roboto-Bold',
        color: theme.colors.critical,
        textTransform: 'uppercase' as 'uppercase',
        textAlign: 'center' as 'center',
    },
    modalSurface: {
        backgroundColor: theme.colors.lightGraphic,
        width: '90%',
        borderRadius: 10,
        padding: 20,
    },
    modalSurfaceContainer: {
        alignItems: 'center' as 'center',
        marginTop: 15,
    },
    modalWarningContainer: {
        padding: 10,
    },
    modalWarningText: {
        fontSize: 20,
        textAlign: 'center' as 'center',
        fontFamily: 'Roboto-Regular',
    },
    row1col2: {
        flexDirection: 'column' as 'column',
        marginLeft: 5,
        marginRight: 10,
    },
    screenTitleText: {
        fontFamily: 'Roboto-Bold' as 'Roboto-Bold',
        fontSize: 32,
        color: theme.colors.lightText,
        textAlign: 'center' as 'center',
        marginVertical: 10,
    },
    surface: {
        flex: 1,
        flexDirection: 'column' as 'column',
        backgroundColor: theme.colors.primaryBackground,
        paddingVertical: 16,
    },
    textColumn: {
        alignContent: 'flex-start' as 'flex-start',
    },
    tooltipContainer: {
        position: 'relative' as 'relative',
    },
};
export default themedStyles;
