import theme from '@assets/Colors';
import {
    hairlineWidth,
    rowMargin,
    rowPadding,
    screenMarginHorizontal,
    screenMarginVertical,
    screenPaddingHorizontal,
    screenPaddingVertical,
} from './../constants/metrics';
const themedStyles: { [key: string]: any } = {
    activityOverlay: {
        position: 'absolute' as 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: theme.colors.activityIndicatorBackground,
        alignItems: 'center' as 'center',
        justifyContent: 'center' as 'center',
        zIndex: 10,
    },
    buttonRow: {
        flexDirection: 'row' as 'row',
        justifyContent: 'space-between' as 'space-between',
        width: '90%',
        marginTop: 24,
    },
    calendarTheme: {
        backgroundColor: '#003366',
        calendarBackground: '#003366',
        textSectionTitleColor: theme.colors.accent, // days of the week
        selectedDayBackgroundColor: 'black',
        // selectedDayTextColor: 'black', // selected background
        todayTextColor: theme.colors.accent,
        dayTextColor: 'white',
        textDisabledColor: '#888',
        monthTextColor: '#fff',
        arrowColor: '#007AFF',
    },
    cardActiveMeetingPrimary: {
        backgroundColor: theme.colors.activeCard,
    },
    cardColumnCenter: {
        justifyContent: 'center',
    },
    cardColumnDate: {
        padding: 5,
    },
    cardColumnIcons: {
        paddingRight: 5,
        alignItems: 'center',
        justifyContent: 'space-between',
        marginVertical: 5,
    },
    cardColumnText: {
        flex: 1,
        paddingHorizontal: 8,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    cardDateContainer: {
        padding: 1,
    },
    cardDefinitionContainer: {
        flex: 1,
    },
    cardFirstRow: {
        flexDirection: 'row',
        flex: 1,
        marginHorizontal: 5,
        alignItems: 'center',
    },
    cardHistoricMeetingPrimary: {
        backgroundColor: theme.colors.historicCard,
    },
    cardIconContainer: {
        marginTop: 10,
        marginRight: 10,
        alignItems: 'flex-end',
    },
    cardMeetingItem: {
        marginVertical: 5,
        paddingBottom: 5,
        backgroundColor: theme.colors.darkShadow,
        flexDirection: 'row',
        flex: 1,
        borderRadius: 10,
        elevation: 3,
        shadowColor: theme.colors.darkShadow,
        shadowRadius: 4,
        shadowOffset: { width: 1, height: 1 },
        shadowOpacity: 0.4,
    },
    cardMeetingTypeText: {
        fontFamily: 'Roboto-Regular',
        fontSize: 26,
        fontWeight: '600',
    },
    cardRootContainer: {
        marginHorizontal: 10,
    },
    container: {
        flex: 1,
        flexDirection: 'column' as 'column',
        marginHorizontal: screenMarginHorizontal,
        marginVertical: screenMarginVertical,
        backgroundColor: theme.colors.primaryBackground,
    },
    containerContents: {
        paddingTop: 5,
        paddingHorizontal: 10,
    },
    dateContainer: { margin: 5 },
    error: {
        color: theme.colors.critical,
        marginBottom: 8,
    },
    errorText: {
        color: theme.colors.critical,
        marginTop: 4,
        marginBottom: 4,
        fontSize: 14,
    },
    firstRow: {
        flexDirection: 'row' as 'row',
        alignItems: 'center' as 'center',
        justifyContent: 'center' as 'center',
        padding: 0,
        marginVertical: 0,
        marginHorizontal: 0,
    },
    formInput: {
        fontFamily: 'Roboto-Regular',
        fontSize: 16,
        //what
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 6,
        padding: 8,
        marginBottom: 8,
        backgroundColor: '#fff',
    },
    formLabel: {
        fontFamily: 'Roboto-Regular',
        fontSize: 18,
        color: theme.colors.lightText,
        paddingVertical: 0,
    },
    groupContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'stretch',
    },
    groupFormLabel: {
        fontFamily: 'Roboto-Regular',
        color: theme.colors.lightText,
        fontSize: 24,
        // padding: 10,
    },
    groupFormRow: {
        marginBottom: 2,
    },
    groupGenderSelectorContainer: {
        flex: 1,
        alignItems: 'center' as 'center',
    },
    groupGenderSelectorRow: {
        flexDirection: 'row' as 'row',
        alignItems: 'center' as 'center',
        justifyContent: 'center' as 'center',
        padding: 0,
        marginVertical: 0,
        marginHorizontal: 0,
    },
    groupGenderSelectorWrapper: {
        flexDirection: 'row' as 'row',
        borderWidth: 2,
        paddingTop: 5,
        paddingBottom: 5,
        borderColor: theme.colors.darkText, // Use the darkText variable directly, same as darkGraphic',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        backgroundColor: theme.colors.lightGraphic,
        marginVertical: screenMarginVertical,
    },
    groupReadOnlyData: {
        fontFamily: 'Roboto-regular',
        fontSize: 24,
        color: theme.colors.accent,
        paddingBottom: rowPadding,
        marginHorizontal: rowMargin,
        // Avoid flex here so the Text height/width is determined by content
        // which prevents layout collapse where values can become invisible.
        paddingVertical: 4,
        borderBottomWidth: hairlineWidth,
        borderBottomColor: theme.colors.lightGraphic,
    },
    groupReadOnlyLabel: {
        fontFamily: 'Roboto-Bold',
        fontSize: 24,
        color: theme.colors.lightText,
        paddingBottom: rowPadding,
        marginHorizontal: rowMargin,
    },
    input: {
        borderWidth: 1,
        color: theme.colors.darkText,
        borderColor: theme.colors.textBoxBorderColor,
        borderRadius: 6,
        padding: 8,
        backgroundColor: theme.colors.textBoxBackground,
    },
    inputError: {
        borderColor: theme.colors.critical,
    },
    keyboardAvoiding: {
        flex: 1,
    },
    label: {
        fontWeight: 'bold',
        fontSize: 16,
        color: theme.colors.lightText,
    },
    logisticsWrapper: {
        flexDirection: 'row' as 'row',
        borderWidth: 2,
        borderColor: theme.colors.darkText, // Use the darkText variable directly, same as darkGraphic',
        borderRadius: 5,
        backgroundColor: theme.colors.white,
        paddingVertical: 5,
        marginHorizontal: 10,
    },
    mealContainer: {
        flexDirection: 'column' as 'column',
        borderWidth: 2,
        borderColor: theme.colors.lightGraphic, // Use the darkText variable directly, same as darkGraphic',
        borderRadius: 5,
        // backgroundColor: theme.colors.white,
        marginVertical: 0,
        // paddingVertical: 5,
        padding: 5,
        marginHorizontal: 10,
    },
    mealSectionContainer: {
        flex: 1,
        borderWidth: 1,
        borderColor: theme.colors.darkText,
        borderRadius: 10,
        padding: 5,
        marginHorizontal: 10,
        marginVertical: 5,
    },
    mealSectionCountLabelContainer: {
        paddingTop: 5,
        alignItems: 'center',
    },
    mealSectionCountLabelText: {
        fontFamily: 'Roboto-Regular',
        color: theme.colors.darkText,
        fontSize: 18,
        textAlign: 'center',
    },
    mealSectionInputLabel: {
        fontFamily: 'Roboto-Regular',
        color: theme.colors.darkText,
        fontSize: 18,
        marginLeft: 10,
    },
    mealSectionTitleText: {
        fontFamily: 'Roboto-Regular',
        color: theme.colors.darkText,
        fontSize: 20,
    },
    mealWrapper: {
        flexDirection: 'row' as 'row',
        borderWidth: 2,
        borderColor: theme.colors.darkText, // Use the darkText variable directly, same as darkGraphic',
        borderRadius: 5,
        backgroundColor: theme.colors.white,
        marginVertical: 0,
        paddingVertical: 5,
        marginHorizontal: 10,
    },
    meetingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'stretch',
    },
    meetingDateRow: {
        marginVertical: 2,
    },
    meetingDetailsBadgeContainer: {
        marginLeft: 'auto' as 'auto',
        paddingVertical: 0,
        paddingHorizontal: 10,
    },
    meetingDetailsContainer: {
        marginLeft: 20,
    },
    meetingLabel: {
        fontFamily: 'Roboto-Regular',
        color: theme.colors.lightText,
        fontSize: 24,
        fontWeight: '400',
    },
    meetingListError: {
        color: theme.colors.white,
        fontWeight: 'bold' as 'bold',
        backgroundColor: theme.colors.accent,
        padding: 12,
        borderRadius: 8,
    },
    meetingNoGroupsLabelContainer: {
        marginTop: 20,
        marginHorizontal: 10,
        alignItems: 'center' as 'center',
    },
    meetingNoGroupsLabelText: {
        fontFamily: 'Roboto-Bold',
        color: theme.colors.yellow,
        fontSize: 20,
        textAlign: 'center' as 'center',
    },
    meetingNotesContainer: {
        marginTop: 10,
        marginHorizontal: 10,
    },
    meetingSelectorContainer: {
        flex: 1,
        alignItems: 'center' as 'center',
        justifyContent: 'center' as 'center',
    },
    meetingSelectorWrapper: {
        flexDirection: 'row' as 'row',
        borderWidth: 2,
        borderColor: theme.colors.darkText, // Use the darkText variable directly, same as darkGraphic',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        backgroundColor: theme.colors.lightGraphic,
        marginVertical: screenMarginVertical,
    },
    meetingTypeSelectorSelected: {
        backgroundColor: theme.colors.accent,
        borderWidth: 0,
    },
    meetingTypeSelectorSelectedText: {
        color: theme.colors.darkText,
    },
    meetingTypeSelectorUnselected: {
        paddingHorizontal: 8,
        paddingVertical: 6,
        borderRadius: 4,
        backgroundColor: theme.colors.unSelected,
        alignSelf: 'flex-start' as 'flex-start',
        marginHorizontal: '1%',
        minWidth: '30%',
        textAlign: 'center' as 'center',
    },
    meetingTypeSelectorUnselectedText: {
        fontSize: 16,
        fontWeight: '500',
        color: theme.colors.unSelectedText,
        textAlign: 'center' as 'center',
    },
    meetingsContainer: {
        flex: 1,
        alignItems: 'center' as 'center',
        paddingTop: 48,
    },
    meetingsItemContainer: {
        width: '100%',
        paddingHorizontal: 15,
        marginVertical: 8,
    },
    meetingsText: {
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center' as 'center',
        marginBottom: 16,
    },
    modal: {
        flex: 1,
        flexDirection: 'column' as 'column',
        alignItems: 'center' as 'center',
        justifyContent: 'center' as 'center',
        backgroundColor: theme.colors.primaryBackground,
    },
    modalDateContainer: { marginTop: 20 },
    modalDateText: {
        fontSize: 24,
        fontFamily: 'Roboto-Bold',
        textAlign: 'center' as 'center',
    },
    modalHeaderContainer: {
        backgroundColor: theme.colors.primaryBackground,
    },
    modalHeaderText: {
        fontFamily: 'Roboto-Bold' as 'Roboto-Bold',
        fontSize: 28,
        fontWeight: '700',
        color: theme.colors.lightText,
        textAlign: 'center' as 'center',
        paddingTop: 10,
    },
    modalMeetingInfoContainer: {},
    modalMeetingInfoText: {
        fontSize: 18,
        fontFamily: 'Roboto-Medium',
        textAlign: 'center' as 'center',
    },
    modalNoteContainer: {
        marginHorizontal: 20,
    },
    modalNoteText: {
        paddingTop: 20,
        fontSize: 16,
        fontFamily: 'Roboto-Bold',
        color: theme.colors.critical,
        textTransform: 'uppercase' as 'uppercase',
        textAlign: 'center' as 'center',
    },
    modalSurface: {
        backgroundColor: theme.colors.lightGraphic,
        width: '90%',
        borderRadius: 10,
        padding: 20,
    },
    modalSurfaceContainer: {
        alignItems: 'center' as 'center',
        marginTop: 15,
    },
    modalWarningContainer: {
        padding: 10,
    },
    modalWarningText: {
        fontSize: 20,
        textAlign: 'center' as 'center',
        fontFamily: 'Roboto-Regular',
    },
    newGroupContainer: {
        flexGrow: 1,
        paddingTop: screenPaddingVertical,
        alignItems: 'center' as 'center',
        // backgroundColor: theme.colors.yellow,
        paddingBottom: 32,
    },
    newGroupSection: {
        width: '100%',
        padding: screenPaddingHorizontal,
    },
    notesContainer: {
        marginHorizontal: 10,
        marginBottom: 15,
        borderRadius: 5,
        paddingHorizontal: 15,
        backgroundColor: theme.colors.lightGraphic,
    },
    notesText: {
        color: theme.colors.darkText,
        fontFamily: 'Roboto-Regular',
        fontSize: 24,
    },
    openShareButtonContainer: {
        justifyContent: 'center',
        marginLeft: 10,
    },
    openShareContainer: {
        flexDirection: 'row',
        textAlign: 'center',
        justifyContent: 'center',
    },
    openShareGroupsButtonContainer: {
        justifyContent: 'center',
        verticalAlign: 'middle',
        borderWidth: 1,
        borderColor: theme.colors.accent,
    },
    openShareGroupsButtonWrapper: {
        paddingLeft: 20,
        justifyContent: 'center',
    },
    openShareGroupsListFooterContainer: {
        alignItems: 'center',
    },
    openShareGroupsListFooterText: {
        color: theme.colors.accent,
        fontFamily: 'Roboto-Regular',
    },
    openShareGroupsListHeaderContainer: {
        alignItems: 'center',
    },
    openShareGroupsListHeaderText: {
        color: theme.colors.accent,
        fontFamily: 'Roboto-Regular',
    },
    openShareGroupsText: {
        color: theme.colors.lightText,
        fontSize: 20,
        fontWeight: '400',
        fontFamily: 'Roboto-Regular',
        textAlign: 'center',
        paddingVertical: 5,
    },
    openShareSection: {
        borderTopColor: theme.colors.accent,
        borderBottomColor: theme.colors.accent,
        marginHorizontal: 10,
        marginBottom: 5,
        borderBottomWidth: hairlineWidth,
        borderTopWidth: hairlineWidth,
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: screenMarginHorizontal,
        paddingVertical: rowPadding,
    },
    row1col2: {
        flexDirection: 'column' as 'column',
        marginLeft: 5,
        marginRight: 10,
    },
    rowInput: {
        width: '100%',
        paddingVertical: rowPadding,
    },
    safeAreaView: {
        flex: 1,
        backgroundColor: theme.colors.primaryBackground,
    },
    saveButton: {
        marginBottom: 32,
        paddingVertical: 12,
        paddingHorizontal: 32,
        backgroundColor: theme.colors.saveButtonBackground,
        borderRadius: 8,
        alignSelf: 'center' as 'center',
    },
    saveText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold' as 'bold',
    },
    screenTitleContainer: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    screenTitleText: {
        fontFamily: 'Roboto-Bold' as 'Roboto-Bold',
        fontSize: 32,
        color: theme.colors.lightText,
        textAlign: 'center' as 'center',
        marginVertical: 10,
    },
    selectorBorder: {
        borderColor: theme.colors.lightGraphic,
        borderWidth: hairlineWidth,
        borderRadius: 5,
        alignItems: 'center' as 'center',
        justifyContent: 'center' as 'center',
    },
    surface: {
        flex: 1,
        flexDirection: 'column' as 'column',
        backgroundColor: theme.colors.primaryBackground,
        paddingVertical: screenPaddingVertical,
        paddingHorizontal: screenPaddingHorizontal,
    },
    textColumn: {
        alignContent: 'flex-start' as 'flex-start',
    },
    tooltipContainer: {
        position: 'relative' as 'relative',
    },
};
export default themedStyles;
